export const PCM_REGISTRY = {
    // CLASSE 1 : COMPTES DE FINANCEMENT PERMANENT
    "1111": "Capital social",
    "1117": "Capital personnel",
    "1118": "Capital souscrit non appelé",
    "1121": "Primes d'émission",
    "1122": "Primes de fusion",
    "1123": "Primes d'apport",
    "1131": "Écarts de réévaluation - immobilisations incorporelles",
    "1132": "Écarts de réévaluation - immobilisations corporelles",
    "1140": "Réserve légale",
    "1151": "Réserves statutaires ou contractuelles",
    "1152": "Réserves facultatives",
    "1161": "Report à nouveau (solde créditeur)",
    "1169": "Report à nouveau (solde débiteur)",
    "1181": "Résultat net en instance d'affectation (solde créditeur)",
    "1189": "Résultat net en instance d'affectation (solde débiteur)",
    "1191": "Résultat net de l'exercice (solde créditeur)",
    "1199": "Résultat net de l'exercice (solde débiteur)",
    "1311": "Subventions d'investissement reçues",
    "1351": "Provisions réglementées pour amortissements dérogatoires",
    "1411": "Emprunts obligataires",
    "1481": "Emprunts auprès des établissements de crédit",
    "1482": "Avances de l'État",
    "1486": "Fournisseurs d'immobilisations (dettes à long terme)",

    // CLASSE 2 : COMPTES D'ACTIF IMMOBILISÉ
    "2111": "Frais de constitution",
    "2113": "Frais d'augmentation du capital",
    "2117": "Frais de prospection",
    "2118": "Autres frais préliminaires",
    "2210": "Brevets, marques, droits et valeurs similaires",
    "2220": "Fonds commercial",
    "2230": "Autres immobilisations incorporelles",
    "2311": "Terrains nus",
    "2313": "Terrains aménagés",
    "2321": "Bâtiments",
    "2323": "Installations complexes spécialisées",
    "2327": "Agencements et aménagements des constructions",
    "2331": "Installations techniques",
    "2332": "Matériel et outillage",
    "2340": "Matériel de transport",
    "2351": "Mobilier de bureau",
    "2352": "Matériel de bureau",
    "2355": "Matériel informatique",
    "2356": "Agencements, matériel et outillage",
    "2380": "Immobilisations corporelles en cours",
    "2392": "Avances et acomptes versés sur commandes d'immobilisations corporelles",
    "2411": "Titres de participation",
    "2481": "Prêts au personnel",
    "2483": "Dépôts et cautionnements versés",

    // CLASSE 3 : COMPTES D'ACTIF CIRCULANT (HORS TRÉSORERIE)
    "3111": "Marchandises",
    "3121": "Matières premières",
    "3122": "Matières et fournitures consommables",
    "3123": "Emballages",
    "3131": "Produits en cours",
    "3141": "Produits intermédiaires",
    "3151": "Produits finis",
    "3411": "Fournisseurs débiteurs, avances et acomptes",
    "3421": "Clients",
    "3424": "Clients douteux ou litigieux",
    "3425": "Clients - Effets à recevoir",
    "3431": "Personnel - avances et acomptes",
    "3451": "Subventions à recevoir",
    "3453": "Acomptes sur impôts sur les résultats",
    "3455": "État - TVA récupérable",
    "3456": "État - TVA récupérable sur immobilisations",
    "3458": "État - Autres comptes débiteurs",
    "3461": "Associés - comptes courants",
    "3481": "Créances sur cessions d'immobilisations",
    "3491": "Charges constatées d'avance",
    "3501": "Actions, partie libérée",
    "3504": "Obligations",
    "3506": "Bons du Trésor",

    // CLASSE 4 : COMPTES DE PASSIF CIRCULANT (HORS TRÉSORERIE)
    "4411": "Fournisseurs",
    "4413": "Fournisseurs - effets à payer",
    "4415": "Fournisseurs - factures non parvenues",
    "4421": "Clients - avances et acomptes reçus sur commandes en cours",
    "4432": "Rémunérations dues au personnel",
    "4433": "Dépôts du personnel créditeurs",
    "4441": "Caisse Nationale de Sécurité Sociale (CNSS)",
    "4443": "Caisses de retraite",
    "4445": "Mutuelles",
    "4453": "État, impôts sur les résultats",
    "4455": "État, TVA facturée",
    "4456": "État, TVA due (suivant déclarations)",
    "4461": "Associés - comptes courants",
    "4481": "Dettes sur acquisitions d'immobilisations",
    "4491": "Produits constatés d'avance",
    "4501": "Provisions pour litiges",
    "4502": "Provisions pour garanties données aux clients",

    // CLASSE 5 : COMPTES DE TRÉSORERIE
    "5111": "Chèques à encaisser ou à l'encaissement",
    "5113": "Effets à encaisser ou à l'encaissement",
    "5141": "Banques (solde débiteur)",
    "5146": "Chèques postaux",
    "5161": "Caisse",
    "5530": "Banques (soldes créditeurs / découverts)",
    "5541": "Crédits de trésorerie",
    "5901": "Virements internes",

    // CLASSE 6 : COMPTES DE CHARGES
    "6111": "Achats de marchandises",
    "6112": "Variations des stocks de marchandises",
    "6114": "Rabais, remises et ristournes obtenus sur achats de marchandises",
    "6121": "Achats de matières premières",
    "6122": "Achats de fournitures consommables",
    "6123": "Achats d'emballages",
    "6124": "Variations des stocks de matières et fournitures",
    "6125": "Achats non stockés de matières et fournitures",
    "6126": "Achats de travaux, études et prestations de services",
    "6131": "Locations et charges locatives",
    "6132": "Redevances de crédit-bail",
    "6133": "Entretien et réparations",
    "6134": "Primes d'assurances",
    "6135": "Rémunérations du personnel extérieur à l'entreprise",
    "6136": "Rémunérations d'intermédiaires et honoraires",
    "6137": "Publicité, publications et relations publiques",
    "6141": "Déplacements, missions et réceptions",
    "6142": "Frais postaux et frais de télécommunications",
    "6144": "Publicité, publications",
    "6145": "Frais de transport",
    "6146": "Cotisations et dons",
    "6161": "Impôts et taxes directs",
    "6165": "Impôts et taxes indirects",
    "6167": "Droits d'enregistrement et de timbre",
    "6171": "Rémunérations du personnel",
    "6174": "Charges sociales",
    "6176": "Assurances de groupe",
    "6181": "Jetons de présence",
    "6182": "Pertes sur créances irrécouvrables",
    "6191": "D.E.A. de l'immobilisation incorporelle",
    "6192": "D.E.A. de l'immobilisation corporelle",
    "6311": "Intérêts des emprunts et dettes",
    "6318": "Autres charges d'intérêts",
    "6331": "Pertes de change",
    "6385": "Charges nettes sur cessions de titres et valeurs de placement",
    "6512": "Valeurs nettes d'amortissements des immobilisations cédées",
    "6581": "Pénalités sur marchés et dédits",
    "6582": "Rappels d'impôts (autres que résultats)",
    "6583": "Pénalités et amendes fiscales ou pénales",
    "6701": "Impôts sur les résultats (IS/IR)",

    // CLASSE 7 : COMPTES DE PRODUITS
    "7111": "Ventes de marchandises au Maroc",
    "7113": "Ventes de marchandises à l'étranger",
    "7118": "Rabais, remises et ristournes accordés par l'entreprise",
    "7121": "Ventes de produits finis",
    "7122": "Ventes de produits intermédiaires",
    "7124": "Ventes de services produits",
    "7125": "Redevances pour brevets, marques et droits similaires",
    "7126": "Prestations de services",
    "7127": "Ventes de produits accessoires",
    "7128": "Rabais, remises et ristournes accordés",
    "7131": "Variation des stocks de produits en cours",
    "7132": "Variation des stocks de produits finis",
    "7140": "Immobilisations produites par l'entreprise elle-même",
    "7161": "Subventions d'exploitation reçues",
    "7181": "Jetons de présence reçus",
    "7182": "Revenus des immeubles non affectés à l'exploitation",
    "7191": "Reprises d'exploitation sur amortissements",
    "7197": "Transferts de charges d'exploitation",
    "7311": "Produits des titres de participation et autres titres immobilisés",
    "7331": "Gains de change",
    "7381": "Intérêts et produits assimilés",
    "7510": "Produits des cessions d'immobilisations",
    "7561": "Libéralités reçues",
    "7571": "Dédits et pénalités reçus",
    "7581": "Remplois de subventions d'investissement"
};

export const getAccountName = (code) => {
    return PCM_REGISTRY[code] || "Compte Personnalisé / Non Répertorié";
};

export const searchAccounts = (query) => {
    if (!query) return [];
    const lowerQuery = query.toLowerCase();
    return Object.entries(PCM_REGISTRY)
        .filter(([code, name]) => code.includes(query) || name.toLowerCase().includes(lowerQuery))
        .slice(0, 10);
};
